### ISSUE TITLE
Error occurs on Hive aggregation 

### ISSUE THREAD

**Issue by Lossless1900** [decster/nativetask#6]
When I try count(*) on Hive, it seems that the reduce part cannot work correct and get unexpected EOF. Error logs are attached.

2013-01-25 09:37:10,905 WARN org.apache.hadoop.hive.conf.HiveConf: hive-site.xml not found on CLASSPATH
2013-01-25 09:37:11,251 INFO ExecReducer: 
&lt;GBY&gt;Id =4
  &lt;Children&gt;
    &lt;SEL&gt;Id =5
      &lt;Children&gt;
        &lt;FS&gt;Id =6
          &lt;Parent&gt;Id = 5 null&lt;\Parent&gt;
        &lt;\FS&gt;
      &lt;\Children&gt;
      &lt;Parent&gt;Id = 4 null&lt;\Parent&gt;
    &lt;\SEL&gt;
  &lt;\Children&gt;
&lt;\GBY&gt;
2013-01-25 09:37:11,251 INFO org.apache.hadoop.hive.ql.exec.GroupByOperator: Initializing Self 4 GBY
2013-01-25 09:37:11,270 INFO org.apache.hadoop.hive.ql.exec.GroupByOperator: Operator 4 GBY initialized
2013-01-25 09:37:11,270 INFO org.apache.hadoop.hive.ql.exec.GroupByOperator: Initializing children of 4 GBY
2013-01-25 09:37:11,270 INFO org.apache.hadoop.hive.ql.exec.SelectOperator: Initializing child 5 SEL
2013-01-25 09:37:11,270 INFO org.apache.hadoop.hive.ql.exec.SelectOperator: Initializing Self 5 SEL
2013-01-25 09:37:11,270 INFO org.apache.hadoop.hive.ql.exec.SelectOperator: SELECT struct&lt;_col0:bigint&gt;
2013-01-25 09:37:11,270 INFO org.apache.hadoop.hive.ql.exec.SelectOperator: Operator 5 SEL initialized
2013-01-25 09:37:11,270 INFO org.apache.hadoop.hive.ql.exec.SelectOperator: Initializing children of 5 SEL
2013-01-25 09:37:11,270 INFO org.apache.hadoop.hive.ql.exec.FileSinkOperator: Initializing child 6 FS
2013-01-25 09:37:11,270 INFO org.apache.hadoop.hive.ql.exec.FileSinkOperator: Initializing Self 6 FS
2013-01-25 09:37:11,314 INFO org.apache.hadoop.hive.ql.exec.FileSinkOperator: Operator 6 FS initialized
2013-01-25 09:37:11,314 INFO org.apache.hadoop.hive.ql.exec.FileSinkOperator: Initialization Done 6 FS
2013-01-25 09:37:11,314 INFO org.apache.hadoop.hive.ql.exec.SelectOperator: Initialization Done 5 SEL
2013-01-25 09:37:11,314 INFO org.apache.hadoop.hive.ql.exec.GroupByOperator: Initialization Done 4 GBY
2013-01-25 09:37:11,323 INFO ExecReducer: ExecReducer: processed 0 rows: used memory = 8644744
2013-01-25 09:37:11,324 INFO org.apache.hadoop.hive.ql.exec.GroupByOperator: 4 finished. closing... 
2013-01-25 09:37:11,324 INFO org.apache.hadoop.hive.ql.exec.GroupByOperator: 4 forwarded 0 rows
2013-01-25 09:37:11,324 INFO org.apache.hadoop.hive.ql.exec.GroupByOperator: 4 forwarding 1 rows
2013-01-25 09:37:11,324 INFO org.apache.hadoop.hive.ql.exec.SelectOperator: 5 forwarding 1 rows
2013-01-25 09:37:11,324 INFO org.apache.hadoop.hive.ql.exec.FileSinkOperator: Final Path: FS hdfs://cloud-03:8020/tmp/hive/hive_2013-01-25_09-36-48_612_2516093428386399976/_tmp.-ext-10001/000000_0
2013-01-25 09:37:11,324 INFO org.apache.hadoop.hive.ql.exec.FileSinkOperator: Writing to temp file: FS hdfs://cloud-03:8020/tmp/hive/hive_2013-01-25_09-36-48_612_2516093428386399976/_task_tmp.-ext-10001/_tmp.000000_0
2013-01-25 09:37:11,331 WARN org.apache.hadoop.io.compress.snappy.LoadSnappy: Snappy native library is available
2013-01-25 09:37:11,331 INFO org.apache.hadoop.io.compress.snappy.LoadSnappy: Snappy native library loaded
2013-01-25 09:37:11,332 INFO org.apache.hadoop.hive.ql.exec.FileSinkOperator: New Final Path: FS hdfs://cloud-03:8020/tmp/hive/hive_2013-01-25_09-36-48_612_2516093428386399976/_tmp.-ext-10001/000000_0.snappy
2013-01-25 09:37:11,378 INFO org.apache.hadoop.hive.ql.exec.SelectOperator: 5 finished. closing... 
2013-01-25 09:37:11,378 INFO org.apache.hadoop.hive.ql.exec.SelectOperator: 5 forwarded 1 rows
2013-01-25 09:37:11,378 INFO org.apache.hadoop.hive.ql.exec.FileSinkOperator: 6 finished. closing... 
2013-01-25 09:37:11,378 INFO org.apache.hadoop.hive.ql.exec.FileSinkOperator: 6 forwarded 0 rows
2013-01-25 09:37:11,438 INFO org.apache.hadoop.hive.ql.exec.SelectOperator: 5 Close done
2013-01-25 09:37:11,438 INFO org.apache.hadoop.hive.ql.exec.GroupByOperator: 4 Close done
2013-01-25 09:37:11,443 INFO org.apache.hadoop.mapred.TaskLogsTruncater: Initializing logs&apos; truncater with mapRetainSize=-1 and reduceRetainSize=-1
2013-01-25 09:37:11,450 ERROR org.apache.hadoop.security.UserGroupInformation: PriviledgedActionException as:root (auth:SIMPLE) cause:java.io.EOFException
2013-01-25 09:37:11,451 WARN org.apache.hadoop.mapred.Child: Error running child
java.io.EOFException
    at java.io.DataInputStream.readInt(DataInputStream.java:375)
    at org.apache.hadoop.io.BytesWritable.readFields(BytesWritable.java:153)
    at org.apache.hadoop.io.serializer.WritableSerialization$WritableDeserializer.deserialize(WritableSerialization.java:67)
    at org.apache.hadoop.io.serializer.WritableSerialization$WritableDeserializer.deserialize(WritableSerialization.java:40)
    at org.apache.hadoop.mapred.Task$ValuesIterator.readNextKey(Task.java:1257)
    at org.apache.hadoop.mapred.Task$ValuesIterator.&lt;init&gt;(Task.java:1193)
    at org.apache.hadoop.mapred.ReduceTask$ReduceValuesIterator.&lt;init&gt;(ReduceTask.java:246)
    at org.apache.hadoop.mapred.ReduceTask.runOldReducer(ReduceTask.java:521)
    at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:432)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:266)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:396)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1113)
    at org.apache.hadoop.mapred.Child.main(Child.java:260)
2013-01-25 09:37:11,455 INFO org.apache.hadoop.mapred.Task: Runnning cleanup for the task

**Comment by decster** [comment]
I think this is because hive use another key type "org.apache.hadoop.hive.ql.io.HiveKey" which is a subclass of BytesWritable, but not exactly BytesWritable,  I have added some code to support this key type of Hive. 
I don't have Hive test environment right now so I havn't validated it yet, you can check out the lastest code to see if this is fixed. Code changes:
https://github.com/decster/nativetask/commit/0c79197bf475bd9762f921b14ee1bd49e04115fa

**Comment by decster** [comment]
Forgot to mention, I also update the prebuild binaries, so just replacing hadoop-nativetask-0.1.0.jar should be fine.

**Comment by Lossless1900** [comment]
Thanks. I'll make a try.

2013/1/25 Binglin Chang notifications@github.com

> Forgot to mention, I also update the prebuild binaries, so just replacing
> hadoop-nativetask-0.1.0.jar should be fine.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/decster/nativetask/issues/6#issuecomment-12690304.

## 

刘牧远

上海交通大学软件学院

上海市闵行区东川路800号 200240

Liu, Muyuan
School of Software
Shanghai Jiao Tong University
800 Dongchuan Road, 200240, Shanghai, China

**Comment by lianhuiwang** [comment]
hi,Binglin
    i have done count(*) on Hive with your jar. that is ok now. so this error is fixed.
thank you very much!
